"""
tests/test_integration.py
==========================
Integration test: runs the full CLI pipeline (pcap → flow_tracker → engine)
against fixture PCAP files and asserts expected alerts fire.

Fixtures are generated by: python tests/fixtures/generate_fixtures.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pytest

try:
    from scapy.all import Ether
    _SCAPY_AVAILABLE = True
except ImportError:
    _SCAPY_AVAILABLE = False

pytestmark = pytest.mark.skipif(
    not _SCAPY_AVAILABLE, reason="scapy not installed"
)

FIXTURES = Path(__file__).parent / "fixtures"
RULES_DIR = Path(__file__).parent.parent / "rules"


def _run_pipeline(pcap_name: str):
    """Return (tracker, engine) after processing a fixture pcap."""
    from capture.pcap_reader import PcapReader
    from detection.flow_tracker import FlowTracker
    from detection.engine import DetectionEngine

    pcap = FIXTURES / pcap_name
    if not pcap.exists():
        pytest.skip(f"Fixture not found: {pcap} — run generate_fixtures.py first")

    tracker = FlowTracker()
    engine = DetectionEngine(rules_dir=RULES_DIR)
    reader = PcapReader(pcap)
    for pkt in reader.read():
        flow = tracker.process_packet(pkt)
        if flow:
            engine.evaluate(flow, pkt)
    engine.finalize(tracker)
    return tracker, engine


# ─────────────────────────────────────────────────────────────────────────────
# HTTP GET — no alerts expected
# ─────────────────────────────────────────────────────────────────────────────

def test_http_get_no_false_positives():
    tracker, engine = _run_pipeline("http_get.pcap")
    assert tracker.flow_count >= 1
    # Should not generate any high/critical alerts on clean traffic
    high_plus = [a for a in engine.alerts if a.severity in ("high", "critical")]
    assert len(high_plus) == 0, f"Unexpected high alerts: {high_plus}"


# ─────────────────────────────────────────────────────────────────────────────
# SQLi — expect HTTP-002 or HTTP-005
# ─────────────────────────────────────────────────────────────────────────────

def test_sqli_pcap_triggers_alert():
    tracker, engine = _run_pipeline("sqli_attempt.pcap")
    rule_ids = {a.rule_id for a in engine.alerts}
    # Should detect either SQLi (HTTP-002) or scanner UA (HTTP-005)
    assert rule_ids & {"HTTP-002", "HTTP-005"}, (
        f"Expected SQLi/UA alert. Got rules: {rule_ids}"
    )


# ─────────────────────────────────────────────────────────────────────────────
# DNS tunnel burst — expect DNS-001, DNS-002, DNS-003, DNS-004
# ─────────────────────────────────────────────────────────────────────────────

def test_dns_tunnel_triggers_alerts():
    tracker, engine = _run_pipeline("dns_tunnel_burst.pcap")
    rule_ids = {a.rule_id for a in engine.alerts}
    # At least one DNS tunneling indicator should fire
    dns_rules = {"DNS-001", "DNS-002", "DNS-003", "DNS-004"}
    assert rule_ids & dns_rules, (
        f"Expected DNS tunneling alert. Got rules: {rule_ids}"
    )


# ─────────────────────────────────────────────────────────────────────────────
# Port scan — expect SCAN-001
# ─────────────────────────────────────────────────────────────────────────────

def test_port_scan_triggers_alert():
    tracker, engine = _run_pipeline("port_scan.pcap")
    rule_ids = {a.rule_id for a in engine.alerts}
    assert "SCAN-001" in rule_ids, (
        f"Expected SCAN-001 port scan alert. Got: {rule_ids}"
    )


# ─────────────────────────────────────────────────────────────────────────────
# Mixed traffic — multiple alert types
# ─────────────────────────────────────────────────────────────────────────────

def test_mixed_traffic_multiple_alerts():
    tracker, engine = _run_pipeline("mixed_traffic.pcap")
    rule_ids = {a.rule_id for a in engine.alerts}
    # Expect at least port scan and at least one HTTP or DNS alert
    assert "SCAN-001" in rule_ids or len(rule_ids) >= 2, (
        f"Expected multiple alert types. Got: {rule_ids}"
    )
    assert tracker.flow_count >= 5


# ─────────────────────────────────────────────────────────────────────────────
# Protocol breakdown sanity check
# ─────────────────────────────────────────────────────────────────────────────

def test_protocol_breakdown_http_get():
    tracker, _ = _run_pipeline("http_get.pcap")
    bd = tracker.protocol_breakdown
    assert "TCP" in bd
    assert bd["TCP"] >= 1


def test_protocol_breakdown_dns_burst():
    tracker, _ = _run_pipeline("dns_tunnel_burst.pcap")
    bd = tracker.protocol_breakdown
    assert "UDP" in bd


# ─────────────────────────────────────────────────────────────────────────────
# Alert severity sanity
# ─────────────────────────────────────────────────────────────────────────────

def test_sqli_alert_severity():
    """SQLi alerts should be high or critical, not low."""
    _, engine = _run_pipeline("sqli_attempt.pcap")
    sqli_alerts = [a for a in engine.alerts if a.rule_id == "HTTP-002"]
    if sqli_alerts:
        assert sqli_alerts[0].severity in ("high", "critical")
